export const FONTS = [
  "Outfit","DM Sans","Syne","Karla","Nunito","Lato","Raleway","Cabin",
  "Barlow","Exo 2","Rubik","Manrope","Plus Jakarta Sans","Lexend","Quicksand",
  "Josefin Sans","Poppins","Work Sans","Mulish","IBM Plex Sans",
  "Merriweather","Playfair Display","Libre Baskerville","PT Serif","Lora",
  "Source Serif 4","Crimson Pro","EB Garamond","Cormorant Garamond",
  "IBM Plex Mono","JetBrains Mono","Fira Code","Source Code Pro",
  "Space Mono","Courier Prime","Anonymous Pro","Inconsolata","Roboto Mono",
  "Ubuntu Mono","Share Tech Mono","Azeret Mono","Red Hat Mono",
  "Comic Neue","Pacifico","Permanent Marker","Special Elite",
  "Caveat","Kalam","Patrick Hand","Architects Daughter",
];

export const DARK_THEMES = [
  {
    id: "obsidian",
    label: "Obsidian",
    accent: "#a5b4fc",
    accentFg: "#0f0e1a",
    bg: "#0d0c17",
    surface: "#13121f",
    surface2: "#1a1929",
    border: "#252338",
    text: "#e2e1f0",
    muted: "#6b6a8a",
  },
  {
    id: "forest",
    label: "Forest",
    accent: "#6ee7b7",
    accentFg: "#052e1c",
    bg: "#080f0c",
    surface: "#0d1710",
    surface2: "#142019",
    border: "#1e3026",
    text: "#d1f0e3",
    muted: "#4a7a62",
  },
  {
    id: "crimson",
    label: "Crimson",
    accent: "#fda4af",
    accentFg: "#1a0608",
    bg: "#110508",
    surface: "#1a0a0d",
    surface2: "#241014",
    border: "#341519",
    text: "#f5d5d9",
    muted: "#7a3d47",
  },
  {
    id: "amber",
    label: "Amber",
    accent: "#fcd34d",
    accentFg: "#1a1000",
    bg: "#0f0c02",
    surface: "#181303",
    surface2: "#221b05",
    border: "#33280a",
    text: "#fef3c7",
    muted: "#7a6520",
  },
  {
    id: "sapphire",
    label: "Sapphire",
    accent: "#93c5fd",
    accentFg: "#051225",
    bg: "#060c18",
    surface: "#0a1422",
    surface2: "#101c2e",
    border: "#192940",
    text: "#dbeafe",
    muted: "#3d6080",
  },
  {
    id: "violet",
    label: "Violet",
    accent: "#c4b5fd",
    accentFg: "#120b28",
    bg: "#0d0818",
    surface: "#130f22",
    surface2: "#1a162e",
    border: "#272040",
    text: "#ede9fe",
    muted: "#6b5fa0",
  },
  {
    id: "teal",
    label: "Teal",
    accent: "#5eead4",
    accentFg: "#042422",
    bg: "#04100f",
    surface: "#071918",
    surface2: "#0c2422",
    border: "#143530",
    text: "#ccfbf1",
    muted: "#3a7a72",
  },
  {
    id: "slate",
    label: "Slate",
    accent: "#94a3b8",
    accentFg: "#0f1520",
    bg: "#0a0d12",
    surface: "#0f141a",
    surface2: "#161c25",
    border: "#212a35",
    text: "#e2e8f0",
    muted: "#4a5568",
  },
];

export const LIGHT_THEMES = [
  {
    id: "paper",
    label: "Paper",
    accent: "#4f46e5",
    accentFg: "#ffffff",
    bg: "#f9f8f5",
    surface: "#ffffff",
    surface2: "#f1f0ec",
    border: "#e2e0d8",
    text: "#1a1a2e",
    muted: "#7070a0",
  },
  {
    id: "meadow",
    label: "Meadow",
    accent: "#059669",
    accentFg: "#ffffff",
    bg: "#f0fdf8",
    surface: "#ffffff",
    surface2: "#e8faf4",
    border: "#d1f0e5",
    text: "#0a2018",
    muted: "#4a8870",
  },
  {
    id: "blush",
    label: "Blush",
    accent: "#e11d48",
    accentFg: "#ffffff",
    bg: "#fff5f7",
    surface: "#ffffff",
    surface2: "#ffe8ed",
    border: "#ffd5dd",
    text: "#2a0a12",
    muted: "#9a4060",
  },
  {
    id: "sand",
    label: "Sand",
    accent: "#b45309",
    accentFg: "#ffffff",
    bg: "#fefce8",
    surface: "#ffffff",
    surface2: "#fef9c3",
    border: "#fde68a",
    text: "#1a1200",
    muted: "#8a6520",
  },
];

export const ALL_THEMES = [...DARK_THEMES, ...LIGHT_THEMES];

export const DEFAULT_SETTINGS = {
  apiKeys: [],        // array of { id, key, label }
  activeKeyIndex: 0,
  colorTheme: "obsidian",
  font: "Outfit",
  model: "gemini-2.5-flash-lite",
  chunkSize: 512,
  chunkOverlap: 64,
  topK: 5,
  temperature: 0.2,
  embedStrategy: "semantic",
};
